`-- TB_BOARD_FILE 
CREATE TABLE BOARD.TB_BOARD_FILE (
	  BOARD_SEQ INT Not Null COMMENT '게시판 번호'
	, FILE_NO INT Not Null COMMENT '파일 번호'
	, FILE_NAME_KEY VARCHAR(200) COMMENT '파일 이름 키'
	, FILE_NAME VARCHAR(100) COMMENT '파일 이름'
	, FILE_PATH VARCHAR(200) COMMENT '파일 경로'
	, FILE_SIZE VARCHAR(50) COMMENT '파일 크기'
	, REMARK VARCHAR(1000) COMMENT '참조'
	, DEL_YN VARCHAR(1) COMMENT '삭제유무'
	, INS_USER_ID VARCHAR(20) COMMENT '입력자 ID'
	, INS_DATE DATETIME COMMENT '입력일시'
	, UPD_USER_ID VARCHAR(20) COMMENT '수정자ID'
	, UPD_DATE DATETIME COMMENT '수정일시'
	, PRIMARY KEY (BOARD_SEQ, FILE_NO) 
) COMMENT '게시판 파일';
 
-- TB_BOARD 
SELECT *
  FROM BOARD.TB_BOARD_FILE;